### PR TITLE
Vertical Resize Gradients

### PR DESCRIPTION
**Pull request by djflan**
Including @catppuccin/core and @sgoudham as this PR might be controversial due to additions.

Relates to: [catppuccin #2029](https://github.com/catppuccin/catppuccin/pull/2029).

For those that do not use VS:

Mocha
image

Machiatto
image

Frappe
image

Latte
image

### CODE REVIEW

**Review by sgoudham — CHANGES_REQUESTED** [review]
Hiya :wave: 

I think as discussed in https://github.com/catppuccin/catppuccin/pull/2029/files, I'd be inclined to say that the vertical gradient should follow the rainbow highlights table (see below for table from style guide). 

E.g. Red -> Yellow/Green -> Lavender

image

**Comment by djflan** [comment]
> Hiya 👋
> 
> I think as discussed in https://github.com/catppuccin/catppuccin/pull/2029/files, I'd be inclined to say that the vertical gradient should follow the rainbow highlights table (see below for table from style guide).
> 
> E.g. Red -> Yellow/Green -> Lavender
> 
> image

So the gardient is limited to 3 colors. If I use red, yellow, and blue - I get:
image

^Definitely don't like that nearly as much. The "Mauve" is needed to anchor it to the borders around it - otherwise it just looks disjointed. The yellow is also way too strong a color here. Rosewater was understated which makes the gradient tolerable.

For the sake of completion, here is rgb:
image

^ Better, but not great.

Contrast those with the original:
image

^ much easier on the eyes. Including the border color first gives a natural flow. The rosewater color lacks the harshness of yellow. The tones are warm enough to feel cozy but not enough to overwhelm. imho :)

Other option is also to not include the gradient. Would be a shame because I think it's awesome, but I could understand the reasoning.

**Comment by sgoudham** [comment]
Thanks for the detailed response! Hard to argue with the points listed and I agree with your analysis!

I'm happy with the gradient of your personal preference. Regarding if the gradient should exist or not, I think it really depends on what users expect in the Visual Studio Theme ecosystem, are other themes including gradients there? Even if they're not, I do think it's quite nice, given how the rest of the UI elements have been themed.

Are users able to toggle the vertical gradient at all?

**Comment by djflan** [comment]
@sgoudham It can be toggled on and off if the windows aren't pinned. For most people, it won't show up. There are other themes using it, most notably [Cyberpunk](https://marketplace.visualstudio.com/items?itemName=T0uchM3.CTVS19). This would be the only gradient shown and its minimal. 

To my knowledge, CP would be the only other theme using it. :)

**Review by sgoudham — APPROVED** [review]
Looks good to me! Once again, thanks for your work!

**Pull request merged**
